services:
################################################################################
# ecmwf-opendata download
################################################################################
  ecmwf-opendata:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: "ecmwf-opendata:0.1"
    container_name: ecmwf-opendata
    volumes:
      - ./data:/app/data
    restart: unless-stopped