services:
################################################################################
# gfs download
################################################################################
  gfs-pubdata:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: "gfs-pubdata:0.1"
    container_name: gfs-pubdata
    volumes:
      - ./data:/app/data
    restart: unless-stopped